---
- name: Start VM
  delegate_to: localhost
  when: vm_start
  community.general.proxmox_kvm:
    node: "{{ vm_node }}"
    api_host: "{{ vm_node_ip }}"
    api_user: "{{ vm_node_api_user }}"
    api_password: "{{ vm_node_api_password }}"
    name: "{{ vm_name }}"
    state: started
  register: start_vm_result

# - name: Set Facts
#   when: vm_start
#   set_fact:
#     vm:
#       first_time_creation: "{{ create_vm_result.changed }}"
#       already_running: "{{ start_vm_result.changed == false }}"

# - name: Wait for system to become reachable
#   ansible.builtin.wait_for_connection:
#     delay: 30
#     timeout: 300
#   when: vm.already_running == false and vm_start == true