---
- name: Pre install
  import_tasks: 1_pre-install.yaml

- name: Fetch ISO
  import_tasks: 2_fetch-iso.yaml

- name: Upload cloud-init
  import_tasks: 3_upload-cloudinit.yaml

- name: Create VM
  import_tasks: 4_create-vm.yaml

- name: Create Disks
  import_tasks: 5_create_disks.yaml

- name: Start VM
  import_tasks: 6_start_vm.yaml

- name: Wait for VM to be accessible
  import_tasks: 7_wait_for_vm.yaml