#cloud-config
manage_etc_hosts: true
user: "{{ default_user }}"
password: "{{ default_user_password }}"
ssh_authorized_keys:
  - "{{ ssh_public_key}}"
chpasswd:
  expire: False
users:
  - default
package_upgrade: true